name: Cache .cargo directory
description: Caching .cargo directory
runs:
  using: composite
  steps:
    - name: Cache .cargo directory
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/cache/
          ~/.cargo/registry/index/
          ~/.cargo/registry/src/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
