[package]
name = "code-open-server"
version = "0.1.0"
authors = ["Akihiro Shoji <alpha.kai.net@alpha-kai-net.info>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "=4.1.8"
code-open-common = { path = "../code-open-common" }
dirs = "=5.0.0"
once_cell = "=1.17.1"
rmp-serde = "=1.1.1"
serde = { version = "=1.0.158", features = ["derive"] }
serde_json = "=1.0.94"
