name: Check dependencies order in Cargo.toml

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cargo-sort:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - uses: ./.github/actions/cargo-cache

      - name: Install cargo sort
        run: cargo install cargo-sort

      - name: Run cargo sort
        run: cargo sort -cw
