name: Check dependencies order in Cargo.toml

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cargo-sort:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-sort

      - name: Install cargo sort
        run: cargo install --force cargo-sort

      - name: Run cargo sort
        run: cargo sort -cw
