name: Validate renovate.json

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache .yarn directory
        uses: actions/cache@v3
        with:
          path: |
            ~/.yarn/bin/
          key: ${{ runner.os }}-yarn

      - name: Install Renovate CLI
        run: yarn global add renovate

      - name: Validate renovate.json
        run: renovate-config-validator
